### ISSUE TITLE
CWW work not being credited in profiles

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Snapshot-Chicago#95]
We've moved Chicago Wildlife Watch to the main page, but a user reports that it's not being listed in the "projects worked on," "number of classifications," etc. (probably on this page: https://www.zooniverse.org/projects/current )

The report: http://talk.chicagowildlifewatch.org/#/boards/BCH0000002/discussions/DCH00000n7?page=1&comment_id=54b54381bb7b561be90002a3

Could we add this functionality for CWW, as all other projects have it?

Thanks!

**Comment by DarrenMcRoy** [comment]
(Also, be sure that this gets added to the "ribbon," if that's different from the other things!)

**Comment by DarrenMcRoy** [comment]
Thanks to @parrish for fixing this!!

**Comment by chrissnyder** [comment]
What was it?

**Comment by DarrenMcRoy** [comment]
To quote @parrish : "It was never associated to the zooniverse home project."

**Comment by parrish** [comment]
Ouroboros projects have a zooniverse_id that associates the project to the zooniverse-home project id.  Without the id, it won't make the API calls to zoo home that create those stats.  CWW never had a project id assigned to it.
